version: '3.8'

services:
  # Main API service for development
  itemsapi:
    build:
      context: ./API
      dockerfile: Dockerfile
    container_name: itemsapi
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_URLS=http://+:8080
    profiles:
      - dev

  # Consumer tests service
  consumer-tests:
    build:
      context: .
      dockerfile: ConsumerTests/Dockerfile
    container_name: consumer-tests
    volumes:
      - ./TestResults:/testresults
      - ./ConsumerTests/pacts:/src/ConsumerTests/pacts
    environment:
      - ASPNETCORE_ENVIRONMENT=Test
    profiles:
      - test

  # Provider tests service
  provider-tests:
    build:
      context: .
      dockerfile: ProviderTests/Dockerfile
    container_name: provider-tests
    volumes:
      - ./TestResults:/testresults
      - ./ConsumerTests/pacts:/src/ConsumerTests/pacts
    environment:
      - ASPNETCORE_ENVIRONMENT=Test
    depends_on:
      - itemsapi-test
    profiles:
      - test

  # API service for testing
  itemsapi-test:
    build:
      context: ./API
      dockerfile: Dockerfile
    container_name: itemsapi-test
    ports:
      - "5002:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Test
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_URLS=http://+:8080
    networks:
      - test-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/api/items"]
      interval: 10s
      timeout: 5s
      retries: 3
    profiles:
      - test

networks:
  test-network:
    driver: bridge